// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    month: "January",
    flowers: [
      "Prune roses back by reducing overall plant size 50%",
      "Apply a 1-inch layer of All Purpose Planting Mix to roses",
      "Prune trees, shrubs as needed",
      "Prevent garden weeds by adding weed preventer",
      "Plant cool season annuals - pansies, snapdragons, calendulas, foxgloves, poppies, linaria",
    ],
    lawn: [
      "Pull any weeds in lawn by hand",
      "Apply crabgrass preventer to all lawns",
      "Re seed lawn patches with cool season lawn",
      "Fertilize cool season lawns - bluegrass, ryegrass",
      "Maintain your lawnmovwer",
      "Install new air filter",
      "Clean mowing deck",
      "Sharpen blade",
      "Change oil",
      "Grease fittings",
      "Clean carburetor",
      "Replace spark plug",
    ],
  },
  {
    id: 2,
    month: "February",
    flowers: [
      "Rose food cycle begins now and every 6-8 weeks after deadheading (Dr Earth)",
      "Apply Bonide Rose Rx 3-In-1 Spray at the first sign of aphids or powdery mildew",
      "Citrus are hungry, fertilize about 2-feet from the trunk and water",
      "Cut back woody overgrown perennials",
      "Prepare spring flowerbeds by working compost or other organic material into the soil",
      "Plant strawberries now",
      "Plant bulbs of gladiola now for spectacular summer color",
      "Mulch garden with 2-3 inches mulch",
      "Control snails with organic bait",
    ],
    lawn: [
      "Pre-emergent herbicide apply to lawn, beds and borders. Don’t apply where planting seeds.",
    ],
  },
  {
    id: 3,
    month: "March",
    flowers: [
      "Fertilize roses and perennials",
      "Fertilize spring bulbs before they start showing",
      "Fertilize citrus and continue through warm months of the year",
      "Deadhead flowers on spring blooming bulbs",
      "Control snails and set bait for ants",
      "Plant warm-season annual flowers (marigolds, petunias)",
      "Plant container grown trees, shrubs, perennial flowers, perennial herbs, and ground covers. Use slow release fertilizer at planting time to top inch or so of soil.",
      "Now is the best time to buy summer bulbs like Gladiola, Cannas, Iris, Dahlias and Lilies. Wait until mid-April to plant",
    ],
    lawn: [
      "Apply fertilizer to wake up warm season lawns and to feed still growing cool season grasses",
      "Mow lawn set lawnmower height to 2 inches",
    ],
  },
  {
    id: 4,
    month: "April",
    flowers: [
      "Fertilize roses, citrus and irises",
      "Blast spider mites with garden hose",
      "Release good bugs like ladybugs and praying mantis",
      "Replace winter season color (pansies and cyclamen) with warm season plants (geraniums, marigolds, impatients, petunias)",
      "Plant summer bloomers like Gladioli, Dahlias, and Lilies",
    ],
    lawn: [
      "De-thatch warm season lawns once it starts to grow in early spring",
      "Start mowing lawn late spring",
    ],
  },
  {
    id: 5,
    month: "May",
    flowers: [
      "Prune winter and spring flowering trees and shrubs once they start blooming",
      "Prune carolina jessamine, hardenbergia, to shape it properly",
      "Apply layer of mulch on flower beds and around trees and shrubs 2-3 inches around base of plants",
    ],
    lawn: [
      "Aerate hard soil",
      "Plant new lawn or reseed, use topper soil",
      "Fertilize lawn",
      "Keep mowing during summer (avoid removing more than 1/3 total length)",
      "Keep mower height to 2 inches (change to 3 when temps reach above 90)",
      "Water 1 inch per week",
    ],
  },
  {
    id: 6,
    month: "June",
    flowers: [
      "Deadhead fading flower blossoms",
      "Watch for fungal disease on tomatoes and roses and spray with a fungicide",
      "Look out for aphids or whitefly (treat with insecticidal soap), spider mites (treat with pyriterums)",
      "Feed flowers w/all purpose food",
      "Plant heat loving veggies like pumpkin",
      "Plant late summer flowering annuals and perennials",
      "Plant tropical shrubs and vines like Bougainvillea, Hibiscus, and Mandevilla",
    ],
    lawn: [
      "Use long acting grub killer to stop grubs",
      "Inspect for damaged sprinkler heads and replace as needed",
    ],
  },
  {
    id: 7,
    month: "July",
    flowers: [
      "Keep deadheading",
      "Give trees shrubs and perennials occasional water down to wash off dust and pests",
      "If annuals or perennials get scraggly consider cutting back by 1/3",
      "Fertilize containers",
      "Fertilize tomatoes",
      "Plant late summer flowers",
    ],
    lawn: [
      "Water early morning to prevent evaporation",
      "Fertilize lawn with high nitrogen mix",
    ],
  },
  {
    id: 8,
    month: "August",
    flowers: [
      "Continue to fertilize roses",
      "Prune back all roses by one half to prepare them for fall",
      "Evaluate garden..notice what is doing well, and what is not. This is the challenging season!",
    ],
    lawn: [
      "Water! Early morning",
      "Try leaving healthy grass clippings to add nitrogen to lawn",
    ],
  },
  {
    id: 9,
    month: "September",
    flowers: [
      "Fertilize roses to encourage fall bloom",
      "Fall planting season begins!",
      "Plant cool season flowers - Mums, Snapdragon, Pansies, Violas, Stock, Poppies, Primrose, Sweet pea, Cyclamen, Calendula, Candytuft, Foxgloves, Sweet Alyssum",
      "Divide or plant perennials now that will bloom in spring or early and mid summer (irisis)",
    ],
    lawn: [
      "Fertilize warm season lawn, Bermuda grass",
      "Stop fertilizing cool season lawns like bluegrass",
    ],
  },
  {
    id: 10,
    month: "October",
    flowers: [
      "Feed roses",
      "Cut back geraniums to prevent leggy growth",
      "Set water irrigation to water less frequently per week",
      "Reduce water for citrus to prepare them for dormancy",
      "Prune trees to prepare for winter growth",
      "Plant annuals like mums, aster, pansies, marigolds, calendula, and perennials",
      "Plant ground covers, herbs, roses, trees, shrubs, lillies",
      "Plant cool season veggies - dill, cilantro, parsley",
    ],
    lawn: [
      "Mow lawn short",
      "Stop feeding and watering the Bermuda lawn",
      "Time to de thatch if needed and aerate lawn again",
      "Overseed lawn with annual ryegrass (Bermuda goes dormant in winter and turns brown so you can overseed with annual ryegrass which will grow and stay green during the cooler months, then will die back once Bermuda grass starts turning green again",
      "Apply pre-emergence herbicide (mid Oct to mid Nov) to prevent winter weeds",
    ],
  },
  {
    id: 11,
    month: "November",
    flowers: [
      "Best rose blooms this month",
      "Stop fertilizing roses so they can go dormant in Jan/Feb",
      "Citrus tree only needs to be watered once a month now",
      "Trees watered only ever other week now",
      "Watch for snails and slugs. Set out bait as needed",
      "Prune deciduous fruit trees. After pruning spray with dormant oil to prevent fungal diseases and pest problems",
    ],
    lawn: [],
  },
  {
    id: 12,
    month: "December",
    flowers: [
      "Stop watering roses this month",
      "Good time to transplant flowers. Keep new transplants well watered",
      "Prune fruit trees once they have gone dormant and lost their leaves",
    ],
    lawn: ["Scatter more seed on bare spots of your lawn"],
  },
];
